name: USDK Command Test
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-usdk:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: cd packages/usdk && pnpm install --no-optional --no-frozen-lockfile
      - name: Run USDK command
        run: cd packages/usdk && ./usdk.js --version
